### ISSUE TITLE
Correct location where measurement files are saved by MML for SIRIUS

### ISSUE THREAD

**Issue by xresende** [lnls-fac/MatlabMiddleLayer#23]
Right now LOCO files and others are being saved into _/MML/Release/achine/SIRIUS.V10_, for example.

**Comment by anacso17** [comment]
-This issue was duplicated in #27 
-Fixed with [`73fca7d`](https://github.com/lnls-fac/MatlabMiddleLayer/commit/73fca7df26d464fdfe0f25a56f263a8b520dc6e8)
