### ISSUE TITLE
'measrespmat' script saves data on a wrong path

### ISSUE THREAD

**Issue by anacso17** [lnls-fac/MatlabMiddleLayer#27]
'measrespmat' script saves data on path '/home/fac_files/lnls-fac/MatlabMiddleLayer/Release/machine'. Right path would be '/home/fac_files/lnls-fac/MatlabMiddleLayer/Release/machine/SIRIUS/'.

**Comment by xresende** [comment]
this is issue is confirmed for SI version  'SI.V22.02'

**Comment by anacso17** [comment]
Fixed by commit [`73fca7d`](https://github.com/lnls-fac/MatlabMiddleLayer/commit/73fca7df26d464fdfe0f25a56f263a8b520dc6e8)
